### ISSUE TITLE
Añadir API para mostrar encuestas de profesor

### ISSUE THREAD

**Issue by pablosalinasc** [IHC-2-2015/manuel_api#12]
Necesitamos que se cree un get en la API que pida el id del profesor y entregue las plantillas asociadas a ese profesor mas las plantillas generales, o sea que no tienen asignado un id de profesor.

**Comment by IanMejias** [comment]
En progreso :construction_worker:

**Comment by IanMejias** [comment]
Casi lista, solo falta integrar la consulta con `master` y subirla a Heroku @carovasquez7
