### ISSUE TITLE
Agregar campo de nombre de encuesta a la API-046

### ISSUE THREAD

**Issue by pablosalinasc** [IHC-2-2015/manuel_api#14]
Cabe destacar que el campo de nombre de la encuesta a publicar será exclusivo de dicha publicación,  por lo tanto no se debe cambiar el nombre de la plantilla en sí.

**Comment by IanMejias** [comment]
En progreso :construction_worker:

**Comment by IanMejias** [comment]
Se soluciona la petición #14 y se modifica la consulta de la
API-046: Publicar encuesta. Los nuevos datos que recibe la consulta son:
- `curso_id` : Es el curso al cual se quiere enviar la evaluación
- `encuesta_id` : Es la plantilla que se quiere utilizar para
  instanciar
  la evaluación
- `nombre` : Es el nombre que el profesor elige para la evaluación

Un ejemplo de POST para la consulta es el siguiente

``` javascript
$http.post("http://manuel-api.herokuapp.com/evaluaciones",{
    contestada: false
    curso_id: 1,
    encuesta_id: 1,
    nombre: "Sprint 1"
})
```

Este POST creará una instancia de la encuesta 360 para el curso 1, la
cual tendrá como nombre resultante "Encuesta 360 - Sprint 1", ya que
Rails concatena el nombre de la encuesta con el nombre que el profesor
eligió para la evaluación.

**Comment by pablosalinasc** [comment]
En manuel-api2.herokuapp.com donde están subiendo los cambios, no funciona la API-046
