### ISSUE TITLE
Modificar API-040 (Asignar como ayudante)

### ISSUE THREAD

**Issue by pablosalinasc** [IHC-2-2015/manuel_api#18]
La idea es que al asignar un ayudante se reemplace por el ayudante anteriormente asignado.

**Comment by IanMejias** [comment]
Por favor sigue el estándar que mandé

EDIT: El título debe decir, por ejemplo, Modificar API-040 y en la descripción poner todo lo necesario

**Comment by carovasquez7** [comment]
Por favor, cuando realices petición, sigue el estándar 
"El  título  NO debe  indicar  el  objetivo  de  esta  incidencia,  ni  tampoco  por  qué se  debe solucionar el bug (si la incidencia corresponde a un bug), o describir la incidencia. Solo debe indicar qué es lo que se debe hacer."

**Comment by pablosalinasc** [comment]
Modifique la sintaxis de la petición, como se pidió.

**Comment by pablosalinasc** [comment]
He movido la petición a cerrado porque solucione el problema de otra manera, por lo que no es necesario resolver esta petición
