### ISSUE TITLE
Devolver respuesta

### ISSUE THREAD

**Issue by vaskiwi** [IHC-2-2015/manuel_api#19]
Se necesita una consulta que al entregarle los atributos "id encuestador" "id encuestado" "id evaluación" devuelva un json con esos datos de la tabla respuesta, por ejemplo al entregarle "id encuestador" = 6 "id encuestado" = 6 "evaluación" = 1 debería devolver [{"id":51,"encuestado_id":6,"encuestador_id":6,"evaluacion_id":1,"created_at":"2016-01-17T20:37:14.906Z","updated_at":"2016-01-17T20:37:14.906Z"}] entendiendo que si no existe la columna con esos datos, la consulta debería devolver un json vacío ([])

**Comment by claudiaguzman** [comment]
Esto es para solucionar problemas con la consulta MA-031 que se encuentra pendiente del sprint anterior

**Comment by CamilaMarin** [comment]
¿Es para saber si el alumno `encuestador_id` termino de responder la encuesta para el alumno `encuestado_id` ?

**Comment by vaskiwi** [comment]
Si, es para eso
