### ISSUE TITLE
Esta mal hecha la relación entre encuesta y alumno

### ISSUE THREAD

**Issue by vaskiwi** [IHC-2-2015/manuel_api#24]
El alumno debería estar relacionado con la evaluación, que es la instancia de la encuesta dentro del curso al que pertenece el alumno y no con la encuesta directamente. Me refiero específicamente a esta tabla http://manuel-api.herokuapp.com/encuesta_alumnos . Como esta ahora es imposible diferenciar cuando un alumno tiene una misma encuesta en 2 cursos distintos y por lo tanto genera algunos errores como por ejemplo que las consultas http://manuel-api.herokuapp.com/grupo_encuesta_pendiente? y http://manuel-api.herokuapp.com/grupo_encuesta? tengan el mismo resultado. Sin embargo, se entiende que cambiar esto implicaría cambiar gran parte de la base de datos y dado el poco tiempo que queda no debería tener prioridad para este sprint.

**Comment by CamilaMarin** [comment]
Efectivamente esa relación entre alumno y encuesta no aporta mucho, sin embargo actualmente si es posible identificar si el alumno tiene la misma encuesta en dos cursos distintos. Si desean que se modifiquen estas consultas por favor redactar las peticiones correspondientes (como peticiones y no como reclamos). 
Saludos.
