### ISSUE TITLE
Curso asociado a una encuesta

### ISSUE THREAD

**Issue by claudiaguzman** [IHC-2-2015/manuel_api#25]
Es necesario saber el curso asociado a las encuestas pendientes y completadas, ya que la API-002 y API-005 no entregan ese valor. Esto genera una incidencia, ya que el alumno no tiene como saber a que curso esta asociada la encuesta que esta viendo.

**Comment by CamilaMarin** [comment]
En proceso

**Comment by IanMejias** [comment]
Las encuestas no están asociadas a cursos según la BD. A lo más están asociadas a profesores (en caso de que el profesor haya creado una copia de la encuesta con sus preguntas personalizadas). Es mejor que nos digas que necesitas saber/obtener para poder solucionar la petición.
