### ISSUE TITLE
añadir api para dehabilitar Encuesta

### ISSUE THREAD

**Issue by smedinam-btf** [IHC-2-2015/manuel_api#27]
Se requiere de una consulta api de tipo "put" para deshabilitar una encuesta, donde se le entregue como parámetro de entrada el id del la encuesta a deshabilitar. Se recomienda que exista un atributo "estado" que sea de tipo booleano para manejar un valor de "true" para habilitado y "false" para deshabilitado.

**Comment by carovasquez7** [comment]
No esta dentro de una HU
