### ISSUE TITLE
Añadir api que Liste todas las preguntas de la aplicacion 

### ISSUE THREAD

**Issue by smedinam-btf** [IHC-2-2015/manuel_api#28]
Se necesita de una consulta api de tipo "get" que entregue todas las preguntas de la aplicacion, sin importar de qué encuesta es. De esa manera se pueden añadir a nuevas plantillas mediante la creacion de encuestas dinámicas.

**Comment by IanMejias** [comment]
Creo que esta consulta está lista por defecto. Trata de ir a la URL 
http://manuel-api.herokuapp.com/pregunta.json y debería entregarte una lista 
con todas las preguntas en formato json

**Comment by smedinam-btf** [comment]
Perfecto. gracias.
