### ISSUE TITLE
Añadir api para Listar encuestas asociadas a un cierto Tipo de encuestas

### ISSUE THREAD

**Issue by smedinam-btf** [IHC-2-2015/manuel_api#30]
Se necesita de una consulta Api de tipo "get" que Liste todas las encuestas de un cierto tipo de encuestas, recibiendo como argumento el "id" del tipo de encuesta. 
Ejemplo:
Tipo Encuesta: 360
Encuestas asociadas a este Tipo:
- Encuesta 1
- Encuesta prueba 2
- Encuesta 3
  (estas encuestas listadas son las requeridas, listadas mediante esa api, donde se le entrega la id del tipo "360")

**Comment by IanMejias** [comment]
Ok. En progreso :wrench:

**Comment by IanMejias** [comment]
Solucionado.
Esta consulta recibe el tipo de una encuesta, y devuelve todas las
encuestas de ese tipo en particular.

La URL de la consulta es:

```
<URL_API>/encuestas_por_tipo?tipo_id=1
```
