### ISSUE TITLE
Añadir api para Listar los cursos en donde se encuentra un alumno

### ISSUE THREAD

**Issue by smedinam-btf** [IHC-2-2015/manuel_api#31]
Se requiere de una consulta Api de tipo "get" que Liste los cursos en donde se encuentra un alumno, entregandole como argumento el "id" del alumno.
Ejemplo
Alumno: Carlos salas
Cursos en donde se encuentra:
- Curso pbd
- Curso verano
- Curso 123

**Comment by IanMejias** [comment]
En curso :wrench:
