### ISSUE TITLE
Modificar API-045

### ISSUE THREAD

**Issue by pablosalinasc** [IHC-2-2015/manuel_api#35]
Dado el cambio en la API-054 (probado en manuel-api2.herokuapp.com) donde se agrega el campo de permitido de tipo booleano, que cambia totalmente el sentido de cada tupla (antes una tupla era directamente el permiso a las funcionalidades dadas a un ayudante en un curso, ahora para cada ayudante se genera (en la base de datos) automáticamente todas las tuplas de las funcionalidades, pero con el campo "permitido" en false) por lo que es necesario cambiar la API-045 de asignación de funcionalidades a un put (antes era un post) para así cambiar el valor de "permitido", según convenga asignar o quitar funcionalidades.

Se  sugiere que el formato sea el siguiente:
        $http.put("http://manuel-api2.herokuapp.com/funcionalidad_ayudante",{
          alumno_id: "id del ayudante",
          curso_id: "id del curso",
          funcionalidad_id: "id de la funcionalidad",
          permitido: "true o false"
        })

**Comment by CamilaMarin** [comment]
Si bien las consultas se recibían hasta ayer a las 23:59, se entiende que esta corresponde a una modificación de la petición #21

**Comment by IanMejias** [comment]
Ok. Yo lo veo

**Comment by IanMejias** [comment]
Esto debería estar listo por defecto. De hecho toda modificación que se quiera 
hacer a una fila de alguna tabla, se puede hacer directamente a

```
<API_URL>/<nombre_tabla>?<payload>
```

Es decir, si quieres modificar alguna fila de la tabla 
`funcionalidad_ayudante_cursos` por ejemplo, debes hacer un PUT a la URL:

```
<API_URL>/funcionalidad_ayudante_cursos
```

Y en el controlador del Angular deberías escribir algo como:

``` javascript
$http.put("<API_URL>/funcionalidad_ayudante_cursos",{
    alumno_id: "id del ayudante",
    curso_id: "id del curso",
    funcionalidad_id: "id de la funcionalidad",
    permitido: "true o false"
})
```

**EDIT**: No. Por ahora no funcionaría este método. Tengo que hacer unas 
correcciones a la BD para que funcione de esta forma. Te aviso por el mismo 
medio cuando esté listo.

**Comment by IanMejias** [comment]
@pablosalinasc Se supone que funciona ahora, pero la única manera de probarlo 
es:
1. Actualizando el proyecto localmente
2. Corriendo las migraciones correspondientes con `rake db:migrate` 
3. Probando la consulta en `localhost`
