### ISSUE TITLE
API-040 no funciona en manuel-api2.herokuapp.com

### ISSUE THREAD

**Issue by pablosalinasc** [IHC-2-2015/manuel_api#38]
No se reconoce la URI y envía el siguiente mensaje:
HTTP404: NO ENCONTRADO: el servidor no encontró nada que coincidiera con el URI (identificador uniforme de recursos) solicitado.
(XHR): PUT - http://manuel-api2.herokuapp.com/es_ayudante

**Comment by carovasquez7** [comment]
No se puede atender a la petición por estar fuera de plazo.

**Comment by CamilaMarin** [comment]
@Bangaa no se si influye en esa consulta los cambios que se hicieron en el `curso_alumno.rb`

**Comment by pablosalinasc** [comment]
El problema es que se aplicaron tarde los cambios en manuel-api2.herkuapp.com (después del martes), para comprobar que funcione dicha API poder indicar la incidencia. Además se podría considerar esta petición como la resolución o corrección de una consulta de la mesa de ayuda hecha en el sprint pasado (no se pide una nueva funcionalidad, solo que funcione como antes). Es más, durante el día miércoles antes de las 18:00 aproximadamente estaba funcionando correctamente la API.
