### ISSUE TITLE
Agregar atributos en la tabla Respuesta

### ISSUE THREAD

**Issue by carovasquez7** [IHC-2-2015/manuel_api#7]
- Agregar el atributo `grupo_id` en la tabla Respuesta. Tipo de dato Integer
- Agregar el atributo `Respondida` en la tabla Respuesta: Tipo de dato Boolean

**Comment by IanMejias** [comment]
Esto se agrega para acceder más rápido al grupo que pertenece un alumno.

**Comment by nefertary** [comment]
No agregar columna (atributo) `respondida` a la tabla `respuesta`. Parece que lo vamos a tener que dejar como estaba, porque de esa forma (con la columna `respondida`) no funciona bien.

Ian.
